import type { Metadata } from "next";

import requireUser from "@/lib/requireUser";
import Link from "next/link";
import Sidebar from "@/components/dashboard/Sidebar";
import Header from "@/components/dashboard/Header";

export const metadata: Metadata = {
  title: "Dashbaord",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await requireUser();

  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Header>
          <Link href={"/dashboard/categories"}>Categories</Link>
        </Header>
        <main className="py-4 px-6">{children}</main>
      </body>
    </html>
  );
}
