import type { Metadata } from "next";
import "../../../globals.css";
import { Inter } from "next/font/google";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans", // 3. Set sebagai CSS variable
});
export const metadata: Metadata = {
  title: "Dashbaord",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const {session, user} = await getUser()
  
  if(session && user.role === 'superadmin'){
    return redirect("/dashboard")
  }
  
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
