import type { Metadata } from "next";
import Sidebar from "../../components/dashboard/Sidebar";
import Header from "../../components/dashboard/Header";

import requireUser from "@/lib/requireUser";
import prisma from "@/lib/prisma";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const getRoleUser = async (id: string) => {
  const user = await prisma.user.findUnique({
    where: {
      id
    },
    select: {
      role: true
    }
  })
  
  if(user?.role === "customer") {
    redirect("/")
  }
  
  return user
}


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session =await requireUser();
  const user = await getRoleUser(session.user?.id as string)
  
  if(user?.role === "seller") {
    redirect("/dashboard")
  }

  return (
    <html lang="en">
      <body className={` antialiased`}>
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
          <Sidebar />
          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
            <Header />
            <main className="py-4 px-6">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
