import type { Metadata } from "next";
import Sidebar from "../../components/dashboard/Sidebar";
import Header from "../../components/dashboard/Header";

import requireUser from "@/lib/requireUser";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Dashbaord",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await requireUser();

  return (
    <html lang="en">
      <body className={` antialiased`}>
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
          <Sidebar />
          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
         {children}
          </div>
        </div>
      </body>
    </html>
  );
}
