import type { Metadata } from "next";
import "../../../globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./_components/Sidebar";
import Header from "./_components/Header";
import { getUser } from "@/lib/auth";
import { redirect } from "next/navigation";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans", // 3. Set sebagai CSS variable
});

export const metadata: Metadata = {
  title: "Dashbaord",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session } = await getUser();

  if (!session) {
    return redirect("/dashboard/sign-in");
  }
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex min-h-screen w-full flex-col bg-muted/40">
          <Sidebar />
          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
            <Header />
            <main className="py-4 px-6">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
